from GeneOntologyAnnotation.GOAnotation import GOMolecularFunctionHierarchy
from GeneOntologyAnnotation.GOAnotation import GOTerm
from GeneOntologyAnnotation.GOAnotation import GoMolecularFunction
from GeneOntologyAnnotation.GOAnotation import ProteinManager
